services:
  astro:
    image: ghcr.io/dionis404/goblincodex:latest
    ports:
      - "4321:4321"
    env_file:
      - /opt/goblincodex/.env
    environment:
      - NODE_ENV=production
    networks:
      - shared-net
    restart: unless-stopped

networks:
  shared-net:
    external: true
