name: Build & Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        env:
          DOCKER_BUILDKIT: 0
        run: docker build -t ghcr.io/dionis404/goblincodex:latest -t ghcr.io/dionis404/goblincodex:${{ github.ref_name }} .

      - name: Push image
        run: |
          docker push ghcr.io/dionis404/goblincodex:latest
          docker push ghcr.io/dionis404/goblincodex:${{ github.ref_name }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Portainer webhook
        run: |
          curl -f -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}"
          echo "Deployed successfully"